### ISSUE TITLE
Connection via Crickit's signal I/O pins

### ISSUE THREAD

**Issue by white-glider** [adafruit/Adafruit_CircuitPython_HCSR04#24]
It seems that it's not possible to connect the HC-SR04 to Crickit using its signal I/O pins instead of connecting it directly to the micro-controller.

Apparently this library requires the trigger and echo pins to be [Pin](https://circuitpython.readthedocs.io/en/6.1.x/shared-bindings/microcontroller/index.html#microcontroller.Pin) objects (like in [this](https://github.com/adafruit/Adafruit_CircuitPython_HCSR04/blob/master/examples/hcsr04_simpletest.py) example), but [the recommended way to address Crickit's I/O pins](https://learn.adafruit.com/adafruit-crickit-creative-robotic-interactive-construction-kit/circuitpython-signals) uses [integers](https://github.com/adafruit/Adafruit_CircuitPython_Crickit/blob/master/adafruit_crickit.py). The following CircuitPython code fails on the last line:

```
import adafruit_hcsr04
from adafruit_crickit import crickit

ss = crickit.seesaw

sonar_trigger = crickit.SIGNAL7
sonar_echo = crickit.SIGNAL8

ss.pin_mode(sonar_trigger, ss.OUTPUT)
ss.pin_mode(sonar_echo, ss.INPUT_PULLDOWN)
ss.digital_write(sonar_trigger, True)

sonar = adafruit_hcsr04.HCSR04(trigger_pin=sonar_trigger, echo_pin=sonar_echo)
```

Please, is there any way to use this sensor through Crickit's signal I/O pins? Shouldn't the pins be all treated the same, i.e. be Pin objects instead of integers?

More information is also available in [this](https://discord.com/channels/327254708534116352/537365702651150357/811777142999875584) Discord thread.

Thank you.

**Comment by ladyada** [comment]
it is not fast enough - just isnt possible!
